### ISSUE TITLE
hasClear with no effect

### ISSUE THREAD

**Issue by mluis** [souly1/ion-time-picker#1]
I'm trying to add the clear button with the attribute on the HTML but it doesn't show up.

`<input type="text" placeholder="" ng-model="StartTime" ion-time-picker hasClear="true">`

I've tried with `hasClear="true"` and `hasClear`.

> Ionic Framework Version: 1.1.1
> Ionic CLI Version: 1.7.16
> Ionic App Lib Version: 0.7.3

**Comment by souly1** [comment]
Hi @mluis , nice to e-meet.
So let's try to solve the issue:
Ionic (and angular under it) has several limitations. One of those limitations is that directive attributes (or directives) can use camel case in javascript (aka: hasClear), but in html use hyphen (aka: has-clear).
This can also be seen [here](https://docs.angularjs.org/guide/directive):

> Angular normalizes an element's tag and attribute name to determine which elements match which directives. We typically refer to directives by their case-sensitive camelCase normalized name (e.g. ngModel). However, since HTML is case-insensitive, we refer to directives in the DOM by lower-case forms, typically using dash-delimited attributes on DOM elements (e.g. ng-model).

I myself miss this as well from time to time - in our case that would be using in html: `has-clear="true"`, so try it out and tell me how things worked out.

Thanks

**Comment by mluis** [comment]
Hello! That worked! :-)
Thank you so much.
I will close the issue.

**Comment by souly1** [comment]
Glad to hear and that I could be of assistance!
