### ISSUE TITLE
onSet is not working

### ISSUE THREAD

**Issue by mahesh-vi** [souly1/ion-time-picker#2]
onSet is not working on my ionic project, can you please give me example how to use this directive?

**Comment by souly1** [comment]
Hi @mahesh-vi , could you perhaps paste some code so I'll be able to help more.

P.S The component is based on angular, as such make sure you are using on-set="" and not onSet="" .
Thanks

**Comment by souly1** [comment]
Closing issue due to lack of responsiveness, assume solved. Feel free to reopen if issue persists.
Thanks
