### ISSUE TITLE
Error: unknown provider - unable to resolve a required dependency [FIXED]

### ISSUE THREAD

**Issue by mikkelmoerch** [souly1/ion-time-picker#4]
Just tried to implement the ion-time-picker and stumbled upon this error:
[Error unknown provider](https://docs.angularjs.org/error/$injector/unpr)

The time picker works but the error is thrown nonetheless.

Debugging of this problem showed that when the module 'ion-pickers' is defined it makes a try/catch(err) statement.

In my case i noticed that no error was catched hence the following was computed:
`pickersModule = angular.module("ion-pickers")`

However this is the cause of the error stated above. When trying to run the directive `ionTimePicker` the `$injector` throws an error. 

I fixed it by adding squared brackets to the module declaration. Running this results in a computation with no errors thrown by Angular. But the time-picker does not react to touch-events indicating that it needs the ion-os-scroller and the hmTouchEvent. Adding these to the module declaration, fixed the problem. Here is the code changed (in a prettified version):

`var pickersModule = null;
try {
    pickersModule = angular.module("ion-pickers", ["hmTouchEvents", "ion-os-scroller"])
} catch (err) {
    pickersModule = angular.module("ion-pickers", ["hmTouchEvents", "ion-os-scroller"])
}` 

Not sure of the reason for this behavior, but I though that I should let you know 👍 😄

**Comment by souly1** [comment]
Hi @mikkelmoerch , thanks for the input.
Changing `pickersModule = angular.module("ion-pickers")` to `pickersModule = angular.module("ion-pickers", []..)` is not that great as it changes `requiring` the module to `declaring` the module, thus the need to add hmTouchEvents and ion-os-scroller.
To solve the issue I'd at least need some more info of your system and how things are set up, such as how does the index.html looks and the main module loading as well.

Thanks

**Comment by mikkelmoerch** [comment]
I'm developing an Ionic 1 app.

Due to company discretion I can only show parts of the code:

Linking files in index.html:
![image](https://cloud.githubusercontent.com/assets/14148920/22880118/3d436e6e-f1e1-11e6-996d-c088d9a585c3.png)


Then defining module in app.js:
![image](https://cloud.githubusercontent.com/assets/14148920/22880226/af3a62d4-f1e1-11e6-8800-a2f73f515eb9.png)

**Comment by souly1** [comment]
I'll look into it, thanks
