### ISSUE TITLE
Cannot get time picker to select 24h time

### ISSUE THREAD

**Issue by paulsonoda** [souly1/ion-time-picker#5]
HI I purchased your time picker and it works well except for one aspect.  I cannot get the time to only use 24H clock.  here is the code I am using ...

        <input type="text" class: "rs-right" placeholder="" ng-model="scheduleData.time" ion-time-picker step="15" isWithDaytime = false \>

What is the proper syntax to get the timepicker to force 24H time only?  Thanks.

**Comment by souly1** [comment]
Hi @psonoda, as this is angular.js (aka angular 1) directives and attributes must be lower case, so use:
is-with-daytime="false"
tell me how it goes.
thanks

**Comment by souly1** [comment]
Any update @psonoda ?

**Comment by paulsonoda** [comment]
Thank you for following up. Yes, that fixed my issue.  Thanks again!!!

Paul Sonoda
